/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hirata.view;

import com.hirata.model.Sesion;
import javax.swing.JOptionPane;

/**
 *
 * @author wadev
 */
public class DashboardView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardView.class.getName());

    /**
     * Creates new form MenuPrincipalView
     */
    public DashboardView() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra el Dashboard en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Perfil = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBienvenida.setText("BIENVENIDO ADMINISTRADOR");

        jMenu1.setText("Usuario");
        jMenu1.addActionListener(this::jMenu1ActionPerformed);

        Perfil.setText("Perfil");
        Perfil.addActionListener(this::PerfilActionPerformed);
        jMenu1.add(Perfil);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acciones");
        jMenu2.addActionListener(this::jMenu2ActionPerformed);

        jMenuItem1.setText("Crear Registro");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Gestion y Historial");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblBienvenida)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
        // 1. Validar que realmente exista una sesión activa por seguridad
    if (com.hirata.model.Sesion.rut == null) {
        JOptionPane.showMessageDialog(this, 
            "No se ha encontrado una sesión activa en el sistema.", 
            "Error de Acceso", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 2. Extraer y formatear las variables globales del usuario conectado
    String rutUsuario = com.hirata.model.Sesion.rut;
    String nombreCompleto = com.hirata.model.Sesion.nombre.toUpperCase();
    String rolAsignado = com.hirata.model.Sesion.rol.toUpperCase();
    
    // Si manejas el ID del personal en tu base de datos, lo mostramos también
    int idPersonal = com.hirata.model.Sesion.idPersonal; 

    // 3. Construir la estructura visual del reporte de perfil técnico
    String mensajePerfil = "=========================================\n"
                         + "      HIRATA S.A. - PERFIL DE USUARIO    \n"
                         + "=========================================\n"
                         + "  • ID Funcionario   : " + idPersonal + "\n"
                         + "  • RUT Empleado     : " + rutUsuario + "\n"
                         + "  • Nombre Completo  : " + nombreCompleto + "\n"
                         + "  • Rol en Sistema   : " + rolAsignado + "\n"
                         + "=========================================\n"
                         + " Estado de cuenta    : Conectado / Activo\n"
                         + " Entorno Operativo   : Hito Integrador I  ";

    // 4. Desplegar el cuadro de diálogo flotante con la información cargada
    JOptionPane.showMessageDialog(this, 
        mensajePerfil, 
        "MI PERFIL - TRANSPORTES HIRATA", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_PerfilActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de que deseas cerrar sesión?", 
            "Confirmar Salida", 
            JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            // Limpiamos los datos de la sesión actual
            com.hirata.model.Sesion.limpiarSesion();

            // Reirigimos al Login base
            LoginView login = new LoginView();
            login.setVisible(true);

            // Destruimos la ventana del Dashboard dinámico
            this.dispose(); 
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new IngresoKM().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Registros().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // 1. Capturar el nombre y el rol desde la sesión global
        String nombreUsuario = (com.hirata.model.Sesion.nombre != null) ? com.hirata.model.Sesion.nombre.toUpperCase() : "USUARIO";

        // 2. Modificar dinámicamente los componentes según el Rol
        if (com.hirata.model.Sesion.rol.equals("admin")) {
            // Cambia el JLabel de bienvenida
            lblBienvenida.setText("BIENVENIDO ADMINISTRADOR: " + nombreUsuario);

            // Modifica los JMenuItems copiados del diseñador usando los nombres que ya existen
            jMenuItem1.setText("Crear Registro");
            jMenuItem2.setText("Gestión y Historial");

        } else if (com.hirata.model.Sesion.rol.equals("conductor")) {
            // Cambia el JLabel de bienvenida
            lblBienvenida.setText("BIENVENIDO CONDUCTOR: " + nombreUsuario);

            // Modifica los mismos JMenuItems para el Conductor
            jMenuItem1.setText("Nuevo Registro");
            jMenuItem2.setText("Ver Historial");
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Perfil;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
