/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hirata.view;

import com.hirata.controller.ControladorAdmin;
import com.hirata.controller.ControladorConductor;
import com.hirata.model.Camion;
import com.hirata.model.Sesion;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author wadev
 */
public class IngresoKM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoKM.class.getName());

    ControladorConductor ctrl = new ControladorConductor();
    ControladorAdmin ctrlAdmin = new ControladorAdmin();
    
    /**
     * Creates new form ConductorDashboard
     */
    public IngresoKM() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra el Dashboard en la pantalla
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kmIngresado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cmbCamiones = new javax.swing.JComboBox<>();
        buscarPatente = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        focoPatente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        txtAnio = new javax.swing.JLabel();
        txtModelo = new javax.swing.JLabel();
        txtKM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kmIngresado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kmIngresado.addActionListener(this::kmIngresadoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nuevo kilometraje:");

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("NUEVO REGISTRO DE KILOMETRAJE");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Seleccionar Vehiculo:");

        cmbCamiones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCamiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCamiones.addActionListener(this::cmbCamionesActionPerformed);

        buscarPatente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscarPatente.setText("Buscar");
        buscarPatente.addActionListener(this::buscarPatenteActionPerformed);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Vehiculos Asignados:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Buscar por patente:");

        focoPatente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        focoPatente.addActionListener(this::focoPatenteActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(focoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarPatente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbCamiones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(focoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPatente))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Modelo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Año:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Kilometraje:");

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMarca.setText("------------");
        txtMarca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAnio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnio.setText("------------");
        txtAnio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtModelo.setText("------------");
        txtModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKM.setText("------------");
        txtKM.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Marca:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Datos del vehiculo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAnio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKM))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kmIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(kmIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (Sesion.rol.equals("admin")) {
            jLabel18.setVisible(false);
            cmbCamiones.setVisible(false);
            
        } else if (Sesion.rol.equals("conductor")) {
            jLabel19.setVisible(false);
            focoPatente.setVisible(false);
            buscarPatente.setVisible(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void kmIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmIngresadoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            // Verificacion de seleccion de vehiculo ===========================
            if (Sesion.rol.equals("admin")) {
                if (focoPatente.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Seleccione el vehiculo primero");
                    return;
                }
            } else if (Sesion.rol.equals("conductor")) {
                if (cmbCamiones.getSelectedItem().toString().equals("Seleccionar Vehiculo")) {
                    JOptionPane.showMessageDialog(this, "Seleccione el vehiculo primero");
                    return;
                }
            }
            // =================================================================
            
            // Verificacion de kilomentraje ingresado ==========================
            if (kmIngresado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el kilometraje para registrar");
                return;
            }
            // =================================================================
            
            String patenteTextField = focoPatente.getText();
            String patenteComboBox = cmbCamiones.getSelectedItem().toString();
            int km = Integer.parseInt(kmIngresado.getText());
            
            if (Sesion.rol.equals("admin")) {
                if (ctrlAdmin.registrarKmAdmin(patenteTextField, km)) {
                    JOptionPane.showMessageDialog(this, "Registro exitoso.");
                    cargarDatos(); // Refresca las tablas y el estado
                } else {
                    JOptionPane.showMessageDialog(this, "Error: El KM debe ser mayor al actual o el camión no está activo.");
                }
            } else if (Sesion.rol.equals("conductor")) {
                
                if (ctrl.registrarKilometraje(patenteComboBox, km)) {
                    JOptionPane.showMessageDialog(this, "Registro exitoso.");
                    cargarDatos(); // Refresca las tablas y el estado
                } else {
                    JOptionPane.showMessageDialog(this, "Error: El KM debe ser mayor al actual o el camión no está activo.");
                }
            }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese solo números.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cmbCamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCamionesActionPerformed
        // TODO add your handling code here:
        if (cmbCamiones.getSelectedItem() != null) {
            
            String patenteSeleccionada = cmbCamiones.getSelectedItem().toString();
            
            if (patenteSeleccionada.equals("Seleccionar Vehiculo")) {
                limpiarLabelsAdmin();
            } else {
                // REPARADO: Se invoca la firma correcta expuesta en ControladorAdmin usando getters
                Camion c = ctrlAdmin.obtenerDatosCamionAdmin(patenteSeleccionada);

                if (c != null) {
                    txtMarca.setText(c.getMarca());
                    txtModelo.setText(c.getModelo());
                    txtAnio.setText(String.valueOf(c.getAnio()));
                    txtKM.setText(String.valueOf(c.getKilometrajeAcumulado()));
                }
            }
        }
    }//GEN-LAST:event_cmbCamionesActionPerformed

    private void buscarPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPatenteActionPerformed
        // TODO add your handling code here:
        buscarYMostrarCamion();
    }//GEN-LAST:event_buscarPatenteActionPerformed

    private void focoPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_focoPatenteActionPerformed
        // TODO add your handling code here:
        buscarYMostrarCamion();
    }//GEN-LAST:event_focoPatenteActionPerformed
    
    private void cargarDatos() {
        // 1. Llenar el ComboBox de camiones asignados
        cmbCamiones.removeAllItems();
        cmbCamiones.addItem("Seleccionar Vehiculo");
        for (String patente : ctrl.obtenerCamionesAsignados(Sesion.idPersonal)) {
            cmbCamiones.addItem(patente);
        }
    }
    
    private void buscarYMostrarCamion() {
        String patente = focoPatente.getText().trim().toUpperCase();
        Camion c = ctrlAdmin.obtenerDatosCamionAdmin(patente);

        if (c != null) {
            txtMarca.setText(c.getMarca());
            txtModelo.setText(c.getModelo());
            txtAnio.setText(String.valueOf(c.getAnio()));
            txtKM.setText(String.valueOf(c.getKilometrajeAcumulado()));
            kmIngresado.requestFocus(); 
        } else {
            JOptionPane.showMessageDialog(this, "Camion no encontrado o inactivo.");
            limpiarLabelsAdmin();
        }
    }
    
    private void limpiarLabelsAdmin() {
        txtMarca.setText("------------");
        txtModelo.setText("------------");
        txtAnio.setText("------------");
        txtKM.setText("------------");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoKM().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton buscarPatente;
    private javax.swing.JComboBox<String> cmbCamiones;
    private javax.swing.JTextField focoPatente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kmIngresado;
    private javax.swing.JLabel txtAnio;
    private javax.swing.JLabel txtKM;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtModelo;
    // End of variables declaration//GEN-END:variables
}
