/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hirata.view;

import com.hirata.controller.ControladorEquipos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author wadev
 */
public class MantenimientoEquiposView extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoEquiposView.class.getName());
    private TecnicoDashboard dashboardPadre; // Guarda la referencia del Dashboard
    
    ControladorEquipos ctrlEquipos = new ControladorEquipos();
    int idOrdenActual = -1; // Guardará el ID de la OT con la que estamos trabajando
    
    /**
     * Creates new form ChecklistEntrada
     */
    public MantenimientoEquiposView(TecnicoDashboard parent, boolean modal) {
        super(parent, modal); // Hace que la ventana sea modal (bloquea la de atrás)
        this.dashboardPadre = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtModeloRight = new javax.swing.JLabel();
        txtMarcaRight = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRegistroRight = new javax.swing.JLabel();
        txtCategoriaRight = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDueñoRight = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTecnicoResponsable = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivoIngreso = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbTipoMantenimiento = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cmbEnciende = new javax.swing.JComboBox<>();
        cmbIniciaSO = new javax.swing.JComboBox<>();
        cmbImagen = new javax.swing.JComboBox<>();
        cmbImprime = new javax.swing.JComboBox<>();
        cmbRedWifi = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCarcasa = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbPantalla = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbTeclado = new javax.swing.JComboBox<>();
        cmbTouchPad = new javax.swing.JComboBox<>();
        cmbPuertosUSB = new javax.swing.JComboBox<>();
        cmbBandejas = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        cmbPanelBotones = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtFirmaCliente = new javax.swing.JTextField();
        btnAbrirOrden = new javax.swing.JToggleButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FICHA DE MANTENIMIENTO");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Modelo:");

        jLabel8.setText("Marca:");

        txtModeloRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtModeloRight.setText("- - -");
        txtModeloRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtMarcaRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMarcaRight.setText("- - -");
        txtMarcaRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Registro:");

        txtRegistroRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistroRight.setText("- - -");
        txtRegistroRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCategoriaRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCategoriaRight.setText("- - -");
        txtCategoriaRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Categoria:");

        jLabel21.setText("Dueño:");

        txtDueñoRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDueñoRight.setText("- - -");
        txtDueñoRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Numero de serie: ");

        txtNumeroSerie.addActionListener(this::txtNumeroSerieActionPerformed);

        jLabel5.setText("Tecnico Responsable: ");

        txtTecnicoResponsable.addActionListener(this::txtTecnicoResponsableActionPerformed);

        txtMotivoIngreso.setColumns(20);
        txtMotivoIngreso.setRows(3);
        jScrollPane1.setViewportView(txtMotivoIngreso);

        jLabel23.setText("Motivo de ingreso:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Informacion sobre el  equipo:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Selecionar equipo:");

        jLabel11.setText("Tipo Mantenimiento:");

        cmbTipoMantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventivo", "Correctivo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbTipoMantenimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumeroSerie)
                                    .addComponent(txtTecnicoResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel21)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModeloRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMarcaRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDueñoRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCategoriaRight, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRegistroRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDueñoRight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoriaRight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarcaRight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTecnicoResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloRight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegistroRight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel29.setText("Enciende:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Estado Funcional");

        jLabel30.setText("Inicia SO:");

        jLabel25.setText("Imagen:");

        jLabel26.setText("Imprime:");

        jLabel27.setText("Red/Wifi:");

        cmbEnciende.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO" }));
        cmbEnciende.addActionListener(this::cmbEnciendeActionPerformed);

        cmbIniciaSO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO" }));
        cmbIniciaSO.addActionListener(this::cmbIniciaSOActionPerformed);

        cmbImagen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO" }));
        cmbImagen.addActionListener(this::cmbImagenActionPerformed);

        cmbImprime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO" }));
        cmbImprime.addActionListener(this::cmbImprimeActionPerformed);

        cmbRedWifi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO" }));
        cmbRedWifi.addActionListener(this::cmbRedWifiActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbEnciende, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbIniciaSO, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbImprime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRedWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cmbEnciende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cmbIniciaSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cmbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cmbImprime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cmbRedWifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setText("Teclado:");

        jLabel18.setText("TouchPad:");

        jLabel19.setText("Puertos USB:");

        jLabel20.setText("Bandejas:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estado Fisico");

        cmbCarcasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Dañado", "No Aplica" }));

        jLabel14.setText("Carcasa:");

        cmbPantalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Dañado", "No Aplica" }));

        jLabel15.setText("Pantalla:");

        cmbTeclado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Dañado", "No Aplica" }));

        cmbTouchPad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Dañado", "No Aplica" }));

        cmbPuertosUSB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Dañado", "No Aplica" }));

        cmbBandejas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Dañado", "No Aplica" }));

        jLabel34.setText("Panel/Botones:");

        cmbPanelBotones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Dañado", "No Aplica" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbPuertosUSB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTouchPad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTeclado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPantalla, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCarcasa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBandejas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbCarcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbTouchPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cmbPuertosUSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbBandejas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cmbPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Declaro que el estado del equipo fue verificado al momento de la recepción.");

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Firma Cliente");

        txtFirmaCliente.addActionListener(this::txtFirmaClienteActionPerformed);

        btnAbrirOrden.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAbrirOrden.setText("Asignar y Guardar");
        btnAbrirOrden.addActionListener(this::btnAbrirOrdenActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFirmaCliente)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addGap(152, 152, 152)
                            .addComponent(btnAbrirOrden))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbrirOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirmaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTecnicoResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTecnicoResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTecnicoResponsableActionPerformed

    private void txtNumeroSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroSerieActionPerformed
        // TODO add your handling code here:
        String sn = txtNumeroSerie.getText().trim();

        // Llamamos al controlador para verificar la existencia del equipo
        com.hirata.model.EquipoOficina equipo = ctrlEquipos.verificarYBuscarEquipo(sn);

        if (equipo != null) {
            // Si existe, mostramos sus datos en labels para darle feedback al técnico
            txtMarcaRight.setText(equipo.getMarca());
            txtModeloRight.setText(equipo.getModelo());
            btnAbrirOrden.setEnabled(true); // Habilitamos el flujo de apertura
        } else {
            // Excepción oficial del caso de estudio (RF-06)
            JOptionPane.showMessageDialog(this, 
                "El equipo no está registrado en el sistema. Debe registrarse primero.", 
                "Equipo No Encontrado", 
                JOptionPane.WARNING_MESSAGE);
            btnAbrirOrden.setEnabled(false);
        }
    }//GEN-LAST:event_txtNumeroSerieActionPerformed

    private void txtFirmaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirmaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirmaClienteActionPerformed

    private void btnAbrirOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirOrdenActionPerformed
        // TODO add your handling code here:
        String sn = txtNumeroSerie.getText().trim();
        String rutTecnico = txtTecnicoResponsable.getText().trim();
        String tipoMant = cmbTipoMantenimiento.getSelectedItem().toString().toLowerCase(); // 'preventivo' o 'correctivo'
        String motivo = txtMotivoIngreso.getText().trim();
        String firmaCliente = txtFirmaCliente.getText().trim(); // RUT del cliente

        // 1. Validaciones básicas de campos vacíos (Flujo Alterno)
        if (sn.isEmpty() || rutTecnico.isEmpty() || motivo.isEmpty() || firmaCliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos de texto antes de guardar.", "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Intentar abrir la Orden de Trabajo a través del Controlador
        // Usamos el ID del técnico en sesión como creador y el RUT ingresado para el responsable
        int idTecnicoResponsable = com.hirata.model.Sesion.idPersonal; 
        int idCreadorAutenticado = com.hirata.model.Sesion.idPersonal;

        int idOrdenActual = ctrlEquipos.abrirOrdenTrabajo(tipoMant, firmaCliente, motivo, sn, idTecnicoResponsable, idCreadorAutenticado);

        if (idOrdenActual == -1) {
            // Excepción oficial del documento: Equipo no registrado
            JOptionPane.showMessageDialog(this, "El número de serie '" + sn + "' no existe. Debe registrar el equipo primero.", "Excepción RF-06", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Si la orden se creó con éxito, guardamos el Checklist de Recepción (Masivo)
        try (Connection con = com.hirata.model.MySQLConexion.getConexion()) {
            String sqlCheck = "INSERT INTO checklist_recepcion (id_orden, item, valor) VALUES (?, ?, ?)";

            try (PreparedStatement ps = con.prepareStatement(sqlCheck)) {

                // --- PARTE 1: ESTADO FÍSICO ---
                // Evaluamos si el combo está en "Bueno" (true), de lo contrario es false
                agregarItemLote(ps, idOrdenActual, "Carcasa sin golpes", cmbCarcasa.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Pantalla sin rayaduras", cmbPantalla.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Teclado completo", cmbTeclado.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Touchpad funcional", cmbTouchPad.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Puertos USB operativos", cmbPuertosUSB.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Bandejas en buen estado", cmbBandejas.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Panel/Botones funcionales", cmbPanelBotones.getSelectedItem().toString().equalsIgnoreCase("Bueno"));

                // --- PARTE 2: ESTADO FUNCIONAL ---
                agregarItemLote(ps, idOrdenActual, "Enciende correctamente", cmbEnciende.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Inicia SO", cmbIniciaSO.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Imagen operativa", cmbImagen.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Impresión funcional", cmbImprime.getSelectedItem().toString().equalsIgnoreCase("Bueno"));
                agregarItemLote(ps, idOrdenActual, "Red/Wifi operativa", cmbRedWifi.getSelectedItem().toString().equalsIgnoreCase("Bueno"));

                // 1. Ejecutamos el lote en MySQL
                ps.executeBatch();

                // 2. Avisamos al usuario del éxito
                JOptionPane.showMessageDialog(this, "¡Mantenimiento Registrado!\nOrden de Trabajo #" + idOrdenActual + " guardada con éxito.");

                // 3. ¡AQUÍ ESTÁ LA MAGIA DEL FLUJO!
                if (dashboardPadre != null) {
                    dashboardPadre.actualizarTablaOrdenes(); // Le ordena al Dashboard recargar la tabla
                }

                this.dispose(); // Destruye y cierra esta ventana de la Ficha automáticamente

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el checklist en la base de datos: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAbrirOrdenActionPerformed

    private void cmbEnciendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnciendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnciendeActionPerformed

    private void cmbIniciaSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIniciaSOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIniciaSOActionPerformed

    private void cmbImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImagenActionPerformed

    private void cmbImprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImprimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImprimeActionPerformed

    private void cmbRedWifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRedWifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRedWifiActionPerformed

    // Método auxiliar interno para no repetir código al armar el Batch SQL
    private void agregarItemLote(PreparedStatement ps, int idOrden, String item, boolean esBueno) throws SQLException {
        ps.setInt(1, idOrden);
        ps.setString(2, item);
        ps.setBoolean(3, esBueno); // Guarda TRUE si el combo era 'Bueno', FALSE si era otra cosa
        ps.addBatch();
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAbrirOrden;
    private javax.swing.JComboBox<String> cmbBandejas;
    private javax.swing.JComboBox<String> cmbCarcasa;
    private javax.swing.JComboBox<String> cmbEnciende;
    private javax.swing.JComboBox<String> cmbImagen;
    private javax.swing.JComboBox<String> cmbImprime;
    private javax.swing.JComboBox<String> cmbIniciaSO;
    private javax.swing.JComboBox<String> cmbPanelBotones;
    private javax.swing.JComboBox<String> cmbPantalla;
    private javax.swing.JComboBox<String> cmbPuertosUSB;
    private javax.swing.JComboBox<String> cmbRedWifi;
    private javax.swing.JComboBox<String> cmbTeclado;
    private javax.swing.JComboBox<String> cmbTipoMantenimiento;
    private javax.swing.JComboBox<String> cmbTouchPad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel txtCategoriaRight;
    private javax.swing.JLabel txtDueñoRight;
    private javax.swing.JTextField txtFirmaCliente;
    private javax.swing.JLabel txtMarcaRight;
    private javax.swing.JLabel txtModeloRight;
    private javax.swing.JTextArea txtMotivoIngreso;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JLabel txtRegistroRight;
    private javax.swing.JTextField txtTecnicoResponsable;
    // End of variables declaration//GEN-END:variables
}
