package com.hirata.view;

import com.hirata.controller.ControladorEquipos;
import com.hirata.model.MySQLConexion;
import java.awt.CardLayout;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wadev
 */
public class ProcesoMantenimientoView extends javax.swing.JDialog {
    
    private int idOrdenActual;
    private int idEquipoActual;
    private TecnicoDashboard dashboardPadre;
    private int CardActual = 1;
    private java.awt.CardLayout cardLayout; // Para controlar las pantallas del asistente
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProcesoMantenimientoView.class.getName());

    private DefaultTableModel modelCambios;
    private DefaultTableModel modelUpdates;
    /**
     * Creates new form EjecucionMantenimientoView
     */
    public ProcesoMantenimientoView(TecnicoDashboard parent, boolean modal, int idOT) {
        super(parent, modal);
        this.dashboardPadre = parent;
        this.idOrdenActual = idOT;
        initComponents();
        
        // Inicializamos el CardLayout del contenedor principal
        cardLayout = (java.awt.CardLayout) panelContenedorCards.getLayout();
        
        
        obtenerIdEquipo();
        inicializarTablasTemporales();
        cargarDatosInicialesEquipo();
    }
    
    private void obtenerIdEquipo() {
        String sql = "SELECT id_equipo FROM orden_trabajo WHERE id = ?";
        try (Connection con = MySQLConexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, idOrdenActual);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) this.idEquipoActual = rs.getInt("id_equipo");
        } catch (SQLException e) { e.printStackTrace(); }
    }

    private void inicializarTablasTemporales() {
        // Inicializar tabla de cambios físicos preparados (Hardware)
        String[] colHw = {"ID Viejo", "S/N Viejo", "ID Nuevo", "S/N Nuevo", "Observación"};
        modelCambios = new DefaultTableModel(colHw, 0);
        tblCambiosPreparados.setModel(modelCambios);

        // Inicializar tabla de actualizaciones preparadas (Software)
        String[] colSw = {"ID EqSoft", "Software", "Versión Antigua", "Versión Nueva"};
        modelUpdates = new DefaultTableModel(colSw, 0);
        tblUpdatesPreparados.setModel(modelUpdates);
    }

    private void cargarDatosInicialesEquipo() {
        // 1. Cargar componentes actuales del equipo
        DefaultTableModel modelComp = new DefaultTableModel(new String[]{"ID", "S/N", "Categoría", "Marca"}, 0);
        String sqlComp = "SELECT c.id, c.sn, cat.nombre, c.marca FROM equipo_componentes ec " +
                         "JOIN componentes c ON ec.id_componentes = c.id " +
                         "JOIN categoria_comp cat ON c.id_categoria_comp = cat.id WHERE ec.id_equipo = ?";
        try (Connection con = MySQLConexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sqlComp)) {
            ps.setInt(1, idEquipoActual);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                modelComp.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tblComponentesActuales.setModel(modelComp);
        } catch (SQLException e) { e.printStackTrace(); }

        // 2. Cargar software actual del equipo
        DefaultTableModel modelSoft = new DefaultTableModel(new String[]{"ID EqSoft", "Nombre", "Versión Actual"}, 0);
        String sqlSoft = "SELECT id, nombre, version_actual FROM equipo_software WHERE id_equipo = ?";
        try (Connection con = MySQLConexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sqlSoft)) {
            ps.setInt(1, idEquipoActual);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                modelSoft.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3)});
            }
            tblSoftwareActual.setModel(modelSoft);
        } catch (SQLException e) { e.printStackTrace(); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedorCards = new javax.swing.JPanel();
        cardInicio = new javax.swing.JPanel();
        chkPulsera = new javax.swing.JCheckBox();
        chkLentes = new javax.swing.JCheckBox();
        chkMascarilla = new javax.swing.JCheckBox();
        chkAlfombrilla = new javax.swing.JCheckBox();
        chkGuantes = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        chkRequiereHardware = new javax.swing.JCheckBox();
        chkRequiereSoftware = new javax.swing.JCheckBox();
        chkVerificarDisco = new javax.swing.JCheckBox();
        chkPruebaRAM = new javax.swing.JCheckBox();
        chkVerificarVoltaje = new javax.swing.JCheckBox();
        chkLimpiezaFisica = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cardHardware = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComponentesActuales = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        cmbRepuestosDisponibles = new javax.swing.JComboBox<>();
        btnBuscarCompatibles = new javax.swing.JButton();
        btnAgregarCambio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCambiosPreparados = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cardSoftware = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSoftwareActual = new javax.swing.JTable();
        btnAgregarUpdate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUpdatesPreparados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtNuevaVersion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cardEntrega = new javax.swing.JPanel();
        ejecutarGuardadoFinalYEntrega = new javax.swing.JButton();
        txtRutSupervisor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chkCarcasaOk = new javax.swing.JCheckBox();
        chkLentes1 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelContenedorCards.setLayout(new java.awt.CardLayout());

        chkPulsera.setText("Pulsera Anti-Estatica");
        chkPulsera.addActionListener(this::chkPulseraActionPerformed);

        chkLentes.setText("Lentes de Seguridad");
        chkLentes.addActionListener(this::chkLentesActionPerformed);

        chkMascarilla.setText("Mascarilla para polvo fino");
        chkMascarilla.addActionListener(this::chkMascarillaActionPerformed);

        chkAlfombrilla.setText("Alfombrilla Dielectrica");
        chkAlfombrilla.addActionListener(this::chkAlfombrillaActionPerformed);

        chkGuantes.setText("Guantes de Nitrilo");
        chkGuantes.addActionListener(this::chkGuantesActionPerformed);

        jCheckBox6.setText("Kit de Destornilladores Dielectricos");
        jCheckBox6.addActionListener(this::jCheckBox6ActionPerformed);

        jCheckBox7.setText("Brolla de cerdas suaves");
        jCheckBox7.addActionListener(this::jCheckBox7ActionPerformed);

        jCheckBox8.setText("Alcohol Isopropilico");
        jCheckBox8.addActionListener(this::jCheckBox8ActionPerformed);

        jCheckBox9.setText("Pasta Termica");
        jCheckBox9.addActionListener(this::jCheckBox9ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Elementos de Proteccion Personal");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        chkRequiereHardware.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkRequiereHardware.setText("¿Requiere Cambio de Componente de Hardware?");

        chkRequiereSoftware.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkRequiereSoftware.setText("¿Requiere Actualización de Software?");

        chkVerificarDisco.setText("Verificar Disco");
        chkVerificarDisco.addActionListener(this::chkVerificarDiscoActionPerformed);

        chkPruebaRAM.setText("Prueba RAM");
        chkPruebaRAM.addActionListener(this::chkPruebaRAMActionPerformed);

        chkVerificarVoltaje.setText("Verificar Voltaje");
        chkVerificarVoltaje.addActionListener(this::chkVerificarVoltajeActionPerformed);

        chkLimpiezaFisica.setText("Limpieza Fisica");
        chkLimpiezaFisica.addActionListener(this::chkLimpiezaFisicaActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Procedimiento");

        javax.swing.GroupLayout cardInicioLayout = new javax.swing.GroupLayout(cardInicio);
        cardInicio.setLayout(cardInicioLayout);
        cardInicioLayout.setHorizontalGroup(
            cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardInicioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardInicioLayout.createSequentialGroup()
                        .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMascarilla)
                            .addComponent(chkAlfombrilla)
                            .addComponent(chkGuantes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPruebaRAM)
                            .addComponent(chkVerificarVoltaje)
                            .addComponent(chkLimpiezaFisica)
                            .addComponent(chkVerificarDisco))
                        .addGap(87, 87, 87))
                    .addGroup(cardInicioLayout.createSequentialGroup()
                        .addComponent(chkLentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(115, 115, 115))
                    .addGroup(cardInicioLayout.createSequentialGroup()
                        .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox6)
                            .addComponent(chkPulsera))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(cardInicioLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkRequiereSoftware)
                    .addComponent(chkRequiereHardware))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardInicioLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardInicioLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardInicioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(324, 324, 324))))
        );
        cardInicioLayout.setVerticalGroup(
            cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardInicioLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPulsera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkLentes)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardInicioLayout.createSequentialGroup()
                        .addComponent(chkMascarilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAlfombrilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkGuantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6))
                    .addGroup(cardInicioLayout.createSequentialGroup()
                        .addComponent(chkLimpiezaFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkVerificarVoltaje)
                        .addGap(8, 8, 8)
                        .addComponent(chkPruebaRAM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkVerificarDisco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addGap(31, 31, 31)
                .addComponent(chkRequiereHardware)
                .addGap(18, 18, 18)
                .addComponent(chkRequiereSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        panelContenedorCards.add(cardInicio, "card2");

        jButton2.setText("Siguiente");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        tblComponentesActuales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblComponentesActuales);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Componentes del equipo");

        jButton5.setText("Retroceder");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        cmbRepuestosDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarCompatibles.setText("Buscar Repuesto");
        btnBuscarCompatibles.addActionListener(this::btnBuscarCompatiblesActionPerformed);

        btnAgregarCambio.setText("Agregar cambio");
        btnAgregarCambio.addActionListener(this::btnAgregarCambioActionPerformed);

        tblCambiosPreparados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCambiosPreparados);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Piezas cambiadas");

        javax.swing.GroupLayout cardHardwareLayout = new javax.swing.GroupLayout(cardHardware);
        cardHardware.setLayout(cardHardwareLayout);
        cardHardwareLayout.setHorizontalGroup(
            cardHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHardwareLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(56, 56, 56))
            .addGroup(cardHardwareLayout.createSequentialGroup()
                .addGroup(cardHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardHardwareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardHardwareLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBuscarCompatibles, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cmbRepuestosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnAgregarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardHardwareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardHardwareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(cardHardwareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardHardwareLayout.setVerticalGroup(
            cardHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardHardwareLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRepuestosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCompatibles)
                    .addComponent(btnAgregarCambio))
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(cardHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        panelContenedorCards.add(cardHardware, "card3");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Software instalado actualmente");

        tblSoftwareActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSoftwareActual);

        btnAgregarUpdate.setText("Agregar cambio");
        btnAgregarUpdate.addActionListener(this::btnAgregarUpdateActionPerformed);

        tblUpdatesPreparados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblUpdatesPreparados);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Actualizaciones preparadas");

        jButton6.setText("Retroceder");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton4.setText("Siguiente");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel8.setText("Nueva Version del programa:");

        javax.swing.GroupLayout cardSoftwareLayout = new javax.swing.GroupLayout(cardSoftware);
        cardSoftware.setLayout(cardSoftwareLayout);
        cardSoftwareLayout.setHorizontalGroup(
            cardSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardSoftwareLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(56, 56, 56))
            .addGroup(cardSoftwareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(cardSoftwareLayout.createSequentialGroup()
                        .addGroup(cardSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardSoftwareLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardSoftwareLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(txtNuevaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnAgregarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardSoftwareLayout.setVerticalGroup(
            cardSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardSoftwareLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarUpdate)
                    .addComponent(txtNuevaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(cardSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton4))
                .addGap(15, 15, 15))
        );

        panelContenedorCards.add(cardSoftware, "card6");

        ejecutarGuardadoFinalYEntrega.setText("Terminar Mantenimiento y Cerrar OT");
        ejecutarGuardadoFinalYEntrega.addActionListener(this::ejecutarGuardadoFinalYEntregaActionPerformed);

        txtRutSupervisor.addActionListener(this::txtRutSupervisorActionPerformed);

        jLabel3.setText("Firma Cliente");

        chkCarcasaOk.setText("Carcasa");
        chkCarcasaOk.addActionListener(this::chkCarcasaOkActionPerformed);

        chkLentes1.setText("Pantalla");
        chkLentes1.addActionListener(this::chkLentes1ActionPerformed);

        jCheckBox10.setText("Teclado");
        jCheckBox10.addActionListener(this::jCheckBox10ActionPerformed);

        jCheckBox11.setText("Puertos USB");
        jCheckBox11.addActionListener(this::jCheckBox11ActionPerformed);

        jCheckBox12.setText("Encendido");
        jCheckBox12.addActionListener(this::jCheckBox12ActionPerformed);

        jCheckBox13.setText("Sistema Operativo");
        jCheckBox13.addActionListener(this::jCheckBox13ActionPerformed);

        jCheckBox14.setText("Wifi/Red");
        jCheckBox14.addActionListener(this::jCheckBox14ActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Checklist para entrega");

        jButton7.setText("Retroceder");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jLabel10.setText("Estado Fisico");

        jLabel11.setText("Estado Funcional");

        javax.swing.GroupLayout cardEntregaLayout = new javax.swing.GroupLayout(cardEntrega);
        cardEntrega.setLayout(cardEntregaLayout);
        cardEntregaLayout.setHorizontalGroup(
            cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEntregaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardEntregaLayout.createSequentialGroup()
                        .addComponent(jCheckBox11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cardEntregaLayout.createSequentialGroup()
                        .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox10)
                            .addComponent(chkLentes1)
                            .addComponent(chkCarcasaOk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardEntregaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox12)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jCheckBox13)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))))
            .addGroup(cardEntregaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ejecutarGuardadoFinalYEntrega)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardEntregaLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardEntregaLayout.createSequentialGroup()
                        .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardEntregaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(txtRutSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardEntregaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
            .addGroup(cardEntregaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardEntregaLayout.setVerticalGroup(
            cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEntregaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardEntregaLayout.createSequentialGroup()
                        .addComponent(chkCarcasaOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkLentes1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox11))
                    .addGroup(cardEntregaLayout.createSequentialGroup()
                        .addComponent(jCheckBox12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox14)))
                .addGap(60, 60, 60)
                .addComponent(txtRutSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(cardEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ejecutarGuardadoFinalYEntrega)
                    .addComponent(jButton7))
                .addGap(33, 33, 33))
        );

        panelContenedorCards.add(cardEntrega, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedorCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedorCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkPulseraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPulseraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPulseraActionPerformed

    private void chkLentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLentesActionPerformed

    private void chkMascarillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMascarillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMascarillaActionPerformed

    private void chkAlfombrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlfombrillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAlfombrillaActionPerformed

    private void chkGuantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGuantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkGuantesActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardActual = 1; 
        
        boolean irHw = chkRequiereHardware.isSelected();
        boolean irSw = chkRequiereSoftware.isSelected();

        if (irHw) { 
            CardActual = 2; 
            cardLayout.show(panelContenedorCards, "card3"); // "card3" es tu cardHardware en initComponents
        } else if (irSw) { 
            CardActual = 3; 
            cardLayout.show(panelContenedorCards, "card6"); // "card6" es tu cardSoftware en initComponents
        } else { 
            CardActual = 4; 
            cardLayout.show(panelContenedorCards, "card4"); // "card4" es tu cardEntrega en initComponents
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CardActual = 1; 
        cardLayout.show(panelContenedorCards, "card2"); // Vuelve al inicio
    }//GEN-LAST:event_jButton5ActionPerformed

    private void chkVerificarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVerificarDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVerificarDiscoActionPerformed

    private void chkPruebaRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPruebaRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPruebaRAMActionPerformed

    private void chkVerificarVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVerificarVoltajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVerificarVoltajeActionPerformed

    private void chkLimpiezaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLimpiezaFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLimpiezaFisicaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (chkRequiereHardware.isSelected()) { 
            CardActual = 2; 
            cardLayout.show(panelContenedorCards, "card3"); // Vuelve a hardware si pasó por ahí
        } else { 
            CardActual = 1; 
            cardLayout.show(panelContenedorCards, "card2"); // Si no, vuelve al inicio
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void chkCarcasaOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCarcasaOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCarcasaOkActionPerformed

    private void chkLentes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLentes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLentes1ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void txtRutSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutSupervisorActionPerformed

    private void btnBuscarCompatiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompatiblesActionPerformed
        // TODO add your handling code here:
        int fila = tblComponentesActuales.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un componente de la lista actual.");
            return;
        }
        String categoria = tblComponentesActuales.getValueAt(fila, 2).toString();
        cmbRepuestosDisponibles.removeAllItems();

        // Busca repuestos en bodega que pertenezcan a la misma categoría
        String sql = "SELECT c.id, c.sn FROM componentes c JOIN categoria_comp cc ON c.id_categoria_comp = cc.id " +
                     "WHERE cc.nombre = ? AND c.estado = 'disponible'";
        try (Connection con = MySQLConexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, categoria);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cmbRepuestosDisponibles.addItem(rs.getInt("id") + " - " + rs.getString("sn"));
            }
        } catch (SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnBuscarCompatiblesActionPerformed

    private void btnAgregarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCambioActionPerformed
        // TODO add your handling code here:
        int fila = tblComponentesActuales.getSelectedRow();
        if (fila == -1 || cmbRepuestosDisponibles.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Asegúrese de seleccionar el componente saliente y el repuesto.");
            return;
        }

        int idViejo = (int) tblComponentesActuales.getValueAt(fila, 0);
        String snViejo = tblComponentesActuales.getValueAt(fila, 1).toString();
        
        String[] parts = cmbRepuestosDisponibles.getSelectedItem().toString().split(" - ");
        int idNuevo = Integer.parseInt(parts[0]);
        String snNuevo = parts[1];

        modelCambios.addRow(new Object[]{idViejo, snViejo, idNuevo, snNuevo, "Reemplazo preventivo técnico"});
    }//GEN-LAST:event_btnAgregarCambioActionPerformed

    private void btnAgregarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUpdateActionPerformed
        // TODO add your handling code here:
        int fila = tblSoftwareActual.getSelectedRow();
        String nuevaVer = txtNuevaVersion.getText().trim();
        if (fila == -1 || nuevaVer.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione el programa y escriba la nueva versión.");
            return;
        }

        int idEqSoft = (int) tblSoftwareActual.getValueAt(fila, 0);
        String nombreSoft = tblSoftwareActual.getValueAt(fila, 1).toString();
        String verAntigua = tblSoftwareActual.getValueAt(fila, 2).toString();

        modelUpdates.addRow(new Object[]{idEqSoft, nombreSoft, verAntigua, nuevaVer});
        txtNuevaVersion.setText("");
    }//GEN-LAST:event_btnAgregarUpdateActionPerformed

    private void ejecutarGuardadoFinalYEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarGuardadoFinalYEntregaActionPerformed
        // TODO add your handling code here:
        // Ya no evaluamos ningún "if (CardActual == 4)", ejecutamos directo porque este botón
        // físicamente solo existe en la pantalla de entrega.
        ejecutarGuardadoFinalYEntrega();
    }//GEN-LAST:event_ejecutarGuardadoFinalYEntregaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (chkRequiereSoftware.isSelected()) { 
            CardActual = 3; 
            cardLayout.show(panelContenedorCards, "card6"); // Va a la de software si está marcada
        } else { 
            CardActual = 4; 
            cardLayout.show(panelContenedorCards, "card4"); // Si no, salta directo a la entrega
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardActual = 4; 
        cardLayout.show(panelContenedorCards, "card4"); // Va directo a la entrega final
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (chkRequiereSoftware.isSelected()) { 
            CardActual = 3; 
            cardLayout.show(panelContenedorCards, "card6"); // Vuelve a software
        } else if (chkRequiereHardware.isSelected()) { 
            CardActual = 2; 
            cardLayout.show(panelContenedorCards, "card3"); // Vuelve a hardware
        } else { 
            CardActual = 1; 
            cardLayout.show(panelContenedorCards, "card2"); // Vuelve al inicio
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void ejecutarGuardadoFinalYEntrega() {
        String supervisor = txtRutSupervisor.getText().trim();
        if (supervisor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Precondición Incumplida: El RUT del supervisor es obligatorio para la entrega.", "Error de Firma", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection con = MySQLConexion.getConexion();
        try {
            con.setAutoCommit(false); // Iniciamos el procesamiento transaccional seguro

            // 1. Guardar EPPs vinculados a la OT
            String sqlEpp = "INSERT INTO epp (id_orden_trabajo, pulsera_anti, lentes, mascarilla, alfombrilla, guantes, destornilladores, brocha, alcohol_iso, pasta_termica, firma_supervisor) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            try (PreparedStatement ps = con.prepareStatement(sqlEpp, Statement.RETURN_GENERATED_KEYS)) {
                ps.setInt(1, idOrdenActual);
                ps.setBoolean(2, chkPulsera.isSelected());
                ps.setBoolean(3, chkLentes.isSelected());
                ps.setBoolean(4, chkMascarilla.isSelected());
                ps.setBoolean(5, chkAlfombrilla.isSelected());
                ps.setBoolean(6, chkGuantes.isSelected());
                ps.setBoolean(7, true); ps.setBoolean(8, true); ps.setBoolean(9, true); ps.setBoolean(10, true);
                ps.setString(11, supervisor);
                ps.executeUpdate();
                
                ResultSet rsE = ps.getGeneratedKeys();
                if (rsE.next()) {
                    int idEpp = rsE.getInt(1);
                    // Insertar Procedimientos en lote (checklist)
                    String sqlProc = "INSERT INTO checklist (id_orden_trabajo, id_epp_fk, id_procedimiento_fk, valor) VALUES (?, ?, ?, TRUE)";
                    try (PreparedStatement psP = con.prepareStatement(sqlProc)) {
                        if (chkLimpiezaFisica.isSelected()) { psP.setInt(1, idOrdenActual); psP.setInt(2, idEpp); psP.setInt(3, 1); psP.addBatch(); }
                        if (chkVerificarVoltaje.isSelected()) { psP.setInt(1, idOrdenActual); psP.setInt(2, idEpp); psP.setInt(3, 2); psP.addBatch(); }
                        if (chkPruebaRAM.isSelected()) { psP.setInt(1, idOrdenActual); psP.setInt(2, idEpp); psP.setInt(3, 3); psP.addBatch(); }
                        if (chkVerificarDisco.isSelected()) { psP.setInt(1, idOrdenActual); psP.setInt(2, idEpp); psP.setInt(3, 4); psP.addBatch(); }
                        psP.executeBatch();
                    }
                }
            }

            // 2. Procesar Cambios de Componentes (Hardware si aplica - Recorriendo la JTable)
            for (int i = 0; i < modelCambios.getRowCount(); i++) {
                int idOld = (int) modelCambios.getValueAt(i, 0);
                int idNew = (int) modelCambios.getValueAt(i, 2);
                String obs = modelCambios.getValueAt(i, 4).toString();

                // Llamada directa al SP del script
                String sqlSpHw = "{CALL sp_cambio_componente(?, ?, ?, ?, 'baja')}";
                try (CallableStatement cs = con.prepareCall(sqlSpHw)) {
                    cs.setInt(1, idOrdenActual);
                    cs.setInt(2, idOld);
                    cs.setInt(3, idNew);
                    cs.setString(4, obs);
                    cs.execute();
                }
            }

            // 3. Procesar Actualizaciones de Software (Si aplica - Recorriendo la JTable)
            for (int i = 0; i < modelUpdates.getRowCount(); i++) {
                int idEqSoft = (int) modelUpdates.getValueAt(i, 0);
                String vAnt = modelUpdates.getValueAt(i, 2).toString();
                String vNew = modelUpdates.getValueAt(i, 3).toString();

                String sqlInsSw = "INSERT INTO actualizacion_software (id_orden_trabajo, id_equipo_software, version_anterior, version_nueva, fecha, observacion) VALUES (?, ?, ?, ?, CURDATE(), 'Update exitoso')";
                try (PreparedStatement psS = con.prepareStatement(sqlInsSw)) {
                    psS.setInt(1, idOrdenActual); psS.setInt(2, idEqSoft); psS.setString(3, vAnt); psS.setString(4, vNew);
                    psS.executeUpdate();
                }

                String sqlUpSoft = "UPDATE equipo_software SET version_actual = ?, fecha_instalacion = CURDATE() WHERE id = ?";
                try (PreparedStatement psU = con.prepareStatement(sqlUpSoft)) {
                    psU.setString(1, vNew); psU.setInt(2, idEqSoft);
                    psU.executeUpdate();
                }
            }

            // 4. Firmar y Cerrar la Orden de Trabajo de Oficina
            String sqlClose = "UPDATE orden_trabajo SET estado = 'cerrada', firma_supervisor = ? WHERE id = ?";
            try (PreparedStatement psL = con.prepareStatement(sqlClose)) {
                psL.setString(1, supervisor);
                psL.setInt(2, idOrdenActual);
                psL.executeUpdate();
            }

            con.commit(); // Éxito definitivo en la transacción masiva
            JOptionPane.showMessageDialog(this, "Mantenimiento finalizado con éxito para Hirata S.A.");
            if (dashboardPadre != null) dashboardPadre.actualizarTablaOrdenes();
            this.dispose();

        } catch (SQLException e) {
            try { con.rollback(); } catch (SQLException ex) { ex.printStackTrace(); }
            JOptionPane.showMessageDialog(this, "Fallo crítico en la transacción: " + e.getMessage(), "Error Transaccional", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCambio;
    private javax.swing.JButton btnAgregarUpdate;
    private javax.swing.JButton btnBuscarCompatibles;
    private javax.swing.JPanel cardEntrega;
    private javax.swing.JPanel cardHardware;
    private javax.swing.JPanel cardInicio;
    private javax.swing.JPanel cardSoftware;
    private javax.swing.JCheckBox chkAlfombrilla;
    private javax.swing.JCheckBox chkCarcasaOk;
    private javax.swing.JCheckBox chkGuantes;
    private javax.swing.JCheckBox chkLentes;
    private javax.swing.JCheckBox chkLentes1;
    private javax.swing.JCheckBox chkLimpiezaFisica;
    private javax.swing.JCheckBox chkMascarilla;
    private javax.swing.JCheckBox chkPruebaRAM;
    private javax.swing.JCheckBox chkPulsera;
    private javax.swing.JCheckBox chkRequiereHardware;
    private javax.swing.JCheckBox chkRequiereSoftware;
    private javax.swing.JCheckBox chkVerificarDisco;
    private javax.swing.JCheckBox chkVerificarVoltaje;
    private javax.swing.JComboBox<String> cmbRepuestosDisponibles;
    private javax.swing.JButton ejecutarGuardadoFinalYEntrega;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelContenedorCards;
    private javax.swing.JTable tblCambiosPreparados;
    private javax.swing.JTable tblComponentesActuales;
    private javax.swing.JTable tblSoftwareActual;
    private javax.swing.JTable tblUpdatesPreparados;
    private javax.swing.JTextField txtNuevaVersion;
    private javax.swing.JTextField txtRutSupervisor;
    // End of variables declaration//GEN-END:variables
}
