/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hirata.view;

import com.hirata.controller.ControladorEquipos;
import com.hirata.model.MySQLConexion;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wadev
 */
public class SupervisorDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SupervisorDashboard.class.getName());

    private final ControladorEquipos ctrlEquipos = new ControladorEquipos();
    
    /**
     * Creates new form SoporteDashboard
     */
    public SupervisorDashboard() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        cargarCategoriasCombo();
        cargarResumenStockLabels();
        cargarTablaStock("TODOS");
        cargarTablaHistorialOT();
    }
    
    // --- PESTAÑA 1: LÓGICA DE INVENTARIO ---
    
    private void cargarCategoriasCombo() {
        cmbCategorias.removeAllItems();
        cmbCategorias.addItem("TODOS");
        String sql = "SELECT nombre FROM categoria_comp";
        try (Connection con = MySQLConexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                cmbCategorias.addItem(rs.getString("nombre"));
            }
        } catch (SQLException e) { e.printStackTrace(); }
    }

    private void cargarResumenStockLabels() {
        // Inicializamos textos por defecto
        lblTotalSSD.setText("SSD: 0 un.");
        lblTotalRAM.setText("RAM: 0 un.");
        lblTotalHDD.setText("HDD: 0 un.");
        lblTotalToners.setText("Tóners: 0 un.");

        // Consumimos directamente la vista 'v_stock_por_categoria' de tu script
        String sql = "SELECT categoria, cantidad_disponible FROM v_stock_por_categoria";
        try (Connection con = MySQLConexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                String cat = rs.getString("categoria").toUpperCase();
                int cant = rs.getInt("cantidad_disponible");
                
                if (cat.contains("SSD")) lblTotalSSD.setText("SSD: " + cant + " un.");
                else if (cat.contains("RAM")) lblTotalRAM.setText("RAM: " + cant + " un.");
                else if (cat.contains("HDD")) lblTotalHDD.setText("HDD: " + cant + " un.");
                else if (cat.contains("TÓNER") || cat.contains("TONER")) lblTotalToners.setText("Tóners: " + cant + " un.");
            }
        } catch (SQLException e) { e.printStackTrace(); }
    }

    private void cargarTablaStock(String categoriaFiltro) {
        String[] columnas = {"ID", "S/N Componente", "Categoría", "Marca", "Modelo", "Capacidad"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        
        // Consumimos la vista 'v_bodega' que filtra solo los disponibles
        String sql = "SELECT * FROM v_bodega";
        if (!categoriaFiltro.equals("TODOS")) {
            sql += " WHERE categoria = ?";
        }

        try (Connection con = MySQLConexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            if (!categoriaFiltro.equals("TODOS")) {
                ps.setString(1, categoriaFiltro);
            }
            
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    modelo.addRow(new Object[]{
                        rs.getInt("id"), rs.getString("sn"), rs.getString("categoria"),
                        rs.getString("marca"), rs.getString("modelo"), rs.getString("capacidad")
                    });
                }
            }
            tblStockDisponible.setModel(modelo);
        } catch (SQLException e) { e.printStackTrace(); }
    }
    
    private void cargarTablaHistorialOT() {
        // Usamos el método polimórfico verHistorial que ya lee de 'v_ordenes_trabajo'
        tblHistorialOT.setModel(ctrlEquipos.verHistorial(0));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbCategorias = new javax.swing.JComboBox<>();
        btnFiltrarStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStockDisponible = new javax.swing.JTable();
        lblTotalSSD = new javax.swing.JLabel();
        lblTotalRAM = new javax.swing.JLabel();
        lblTotalHDD = new javax.swing.JLabel();
        lblTotalToners = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorialOT = new javax.swing.JTable();
        btnImprimirPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFiltrarStock.setText("Filtrar");
        btnFiltrarStock.addActionListener(this::btnFiltrarStockActionPerformed);

        tblStockDisponible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStockDisponible);

        lblTotalSSD.setText("SSD: -- unidades");

        lblTotalRAM.setText("RAM: -- unidades");

        lblTotalHDD.setText("HDD: -- unidades");

        lblTotalToners.setText("Tóners: -- unidades");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Control de Inventario");

        jLabel2.setText("Filtrar por categoria:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnFiltrarStock))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalSSD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalHDD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalToners, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltrarStock)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalSSD)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalRAM)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalHDD)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalToners)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventarion - Tab 1", jPanel1);

        tblHistorialOT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblHistorialOT);

        btnImprimirPDF.setText("Imprimir PDF");
        btnImprimirPDF.addActionListener(this::btnImprimirPDFActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnImprimirPDF)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnImprimirPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Registros - Tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarStockActionPerformed
        // TODO add your handling code here:
        String catSeleccionada = cmbCategorias.getSelectedItem().toString();
        cargarTablaStock(catSeleccionada);
    }//GEN-LAST:event_btnFiltrarStockActionPerformed

    private void btnImprimirPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPDFActionPerformed
        // TODO add your handling code here:
        int fila = tblHistorialOT.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden de trabajo para emitir el folio cliente.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idOT = (int) tblHistorialOT.getValueAt(fila, 0);
        generarFolioMantenimientoCliente(idOT);
    }//GEN-LAST:event_btnImprimirPDFActionPerformed

    private void generarFolioMantenimientoCliente(int idOT) {
        String nombreArchivo = "Folio_Mantenimiento_OT_" + idOT + ".txt";
        
        try (Connection con = MySQLConexion.getConexion();
             FileWriter fw = new FileWriter(nombreArchivo);
             PrintWriter pw = new PrintWriter(fw)) {

            // 1. Obtener cabecera de la orden usando la vista general
            String sqlOt = "SELECT * FROM v_ordenes_trabajo WHERE id_ot = ?";
            PreparedStatement psO = con.prepareStatement(sqlOt);
            psO.setInt(1, idOT);
            ResultSet rsO = psO.executeQuery();

            if (rsO.next()) {
                pw.println("=================================================================");
                pw.println("          EMPRESA DE TRANSPORTES HIRATA S.A. - AREA TI          ");
                pw.println("               FOLIO DE ENTREGA DE EQUIPO                       ");
                pw.println("=================================================================");
                pw.println("Nro. Orden Trabajo : " + rsO.getInt("id_ot"));
                pw.println("Fecha Mantenimiento: " + rsO.getDate("fecha"));
                pw.println("Tipo Mantención    : " + rsO.getString("tipo_mantenimiento").toUpperCase());
                pw.println("Estado Final       : " + rsO.getString("estado").toUpperCase());
                pw.println("-----------------------------------------------------------------");
                pw.println("DATOS DEL EQUIPO:");
                pw.println("Nro. Serie (S/N)   : " + rsO.getString("equipo_sn"));
                pw.println("Tipo Dispositivo   : " + rsO.getString("tipo_equipo"));
                pw.println("Marca / Modelo     : " + rsO.getString("equipo_marca") + " " + rsO.getString("equipo_modelo"));
                pw.println("-----------------------------------------------------------------");
                pw.println("Motivo de Ingreso  : " + rsO.getString("motivo"));
                pw.println("Técnico Asignado   : " + rsO.getString("tecnico_responsable"));
                pw.println("RUT Firma Cliente  : " + rsO.getString("firma_cliente"));
                pw.println("RUT Firma Supervisor: " + rsO.getString("rut_creador"));
                pw.println("=================================================================");
            }

            // 2. Adjuntar componentes instalados en este mantenimiento (Trazabilidad)
            pw.println("PIEZAS Y COMPONENTES SUSTITUIDOS / INSTALADOS:");
            String sqlHw = "SELECT cat.nombre, c.marca, c.modelo, c.capacidad, cc.observacion " +
                           "FROM cambio_componente cc " +
                           "JOIN componentes c ON cc.id_comp_nuevo = c.id " +
                           "JOIN categoria_comp cat ON c.id_categoria_comp = cat.id WHERE cc.id_orden_trabajo = ?";
            PreparedStatement psH = con.prepareStatement(sqlHw);
            psH.setInt(1, idOT);
            ResultSet rsH = psH.executeQuery();
            
            boolean tieneHw = false;
            while (rsH.next()) {
                tieneHw = true;
                pw.println(" * [" + rsH.getString("nombre") + "] " + rsH.getString("marca") + " " + rsH.getString("modelo") + " (" + rsH.getString("capacidad") + ") - Obs: " + rsH.getString("observacion"));
            }
            if (!tieneHw) pw.println(" * No se realizaron modificaciones de hardware físico.");
            pw.println("-----------------------------------------------------------------");

            // 3. Adjuntar aplicaciones y sistemas actualizados
            pw.println("SISTEMAS Y APLICACIONES ACTUALIZADAS:");
            String sqlSw = "SELECT s.nombre, s.tipo, ast.version_anterior, ast.version_nueva " +
                           "FROM actualizacion_software ast " +
                           "JOIN equipo_software es ON ast.id_equipo_software = es.id " +
                           "JOIN software s ON es.id_software = s.id WHERE ast.id_orden_trabajo = ?";
            PreparedStatement psS = con.prepareStatement(sqlSw);
            psS.setInt(1, idOT);
            ResultSet rsS = psS.executeQuery();

            boolean tieneSw = false;
            while (rsS.next()) {
                tieneSw = true;
                pw.println(" * [" + rsS.getString("tipo") + "] " + rsS.getString("nombre") + " -> Versión instalada: " + rsS.getString("version_nueva") + " (Antigua: " + rsS.getString("version_anterior") + ")");
            }
            if (!tieneSw) pw.println(" * No se registraron actualizaciones de software en esta orden.");
            pw.println("=================================================================");
            pw.println("    Firma Técnico Responsable          Firma Supervisor Entrega   ");
            pw.println("\n\n   ---------------------------        --------------------------- ");
            pw.println("          Hirata S.A.                         Área Control TI             ");
            pw.println("=================================================================");

            JOptionPane.showMessageDialog(this, "Folio oficial de entrega generado con éxito.\nGuardado como: " + nombreArchivo, "Impresión Exitosa", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fallo al generar el reporte del folio: " + e.getMessage(), "Error de Archivo", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SupervisorDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarStock;
    private javax.swing.JButton btnImprimirPDF;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTotalHDD;
    private javax.swing.JLabel lblTotalRAM;
    private javax.swing.JLabel lblTotalSSD;
    private javax.swing.JLabel lblTotalToners;
    private javax.swing.JTable tblHistorialOT;
    private javax.swing.JTable tblStockDisponible;
    // End of variables declaration//GEN-END:variables
}
